// <auto-generated />
using System;
using MeowsicLabzz.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MeowsicLabzz.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260117081304_NewSeedData")]
    partial class NewSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MeowsicLabzz.Components.Domain.Album", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Albums");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArtistId = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9162),
                            CreatedBy = "System",
                            GenreId = 1,
                            Title = "Happier Than Ever",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9163),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            ArtistId = 2,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9164),
                            CreatedBy = "System",
                            GenreId = 1,
                            Title = "ODDINARY",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9165),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            ArtistId = 3,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9166),
                            CreatedBy = "System",
                            GenreId = 1,
                            Title = "Positions",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9167),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("MeowsicLabzz.Components.Domain.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Artists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9029),
                            CreatedBy = "System",
                            Name = "Billie Eilish",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9029),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9031),
                            CreatedBy = "System",
                            Name = "Stray Kids",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9031),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9033),
                            CreatedBy = "System",
                            Name = "Ariana Grande",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9033),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("MeowsicLabzz.Components.Domain.Friends", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Friends");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Chee Peng",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ding Tan",
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MeowsicLabzz.Components.Domain.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8943),
                            CreatedBy = "System",
                            Name = "Pop",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8944),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8945),
                            CreatedBy = "System",
                            Name = "Rock",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8946),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8947),
                            CreatedBy = "System",
                            Name = "Jazz",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8947),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8949),
                            CreatedBy = "System",
                            Name = "Classical",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8949),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("MeowsicLabzz.Components.Domain.Mood", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Moods");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8843),
                            CreatedBy = "System",
                            Name = "Happy",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8858),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8860),
                            CreatedBy = "System",
                            Name = "Sad",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8861),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8862),
                            CreatedBy = "System",
                            Name = "Energetic",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8863),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8864),
                            CreatedBy = "System",
                            Name = "Chill",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(8864),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("MeowsicLabzz.Components.Domain.MusicDiscovery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SongId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MusicDiscovery");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongId = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SongId = 0,
                            UpdatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            UserId = 0
                        });
                });

            modelBuilder.Entity("MeowsicLabzz.Components.Domain.MyPlaylist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MyPlaylist");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9642),
                            CreatedBy = "System",
                            Description = " ",
                            Name = "Chill Tunes",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9643),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9645),
                            CreatedBy = "System",
                            Description = " ",
                            Name = "Study Music",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9646),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("MeowsicLabzz.Components.Domain.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AlbumId")
                        .HasColumnType("int");

                    b.Property<int>("ArtistId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Songs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AlbumId = 0,
                            ArtistId = 0,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9256),
                            CreatedBy = "System",
                            Duration = 0,
                            GenreId = 0,
                            Title = "Happier Than Ever",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9256),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 2,
                            AlbumId = 0,
                            ArtistId = 0,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9258),
                            CreatedBy = "System",
                            Duration = 0,
                            GenreId = 0,
                            Title = "Bad Guy",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9258),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 3,
                            AlbumId = 0,
                            ArtistId = 0,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9259),
                            CreatedBy = "System",
                            Duration = 0,
                            GenreId = 0,
                            Title = "MANIAC",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9260),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 4,
                            AlbumId = 0,
                            ArtistId = 0,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9261),
                            CreatedBy = "System",
                            Duration = 0,
                            GenreId = 0,
                            Title = "God's Menu",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9261),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 5,
                            AlbumId = 0,
                            ArtistId = 0,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9262),
                            CreatedBy = "System",
                            Duration = 0,
                            GenreId = 0,
                            Title = "positions",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9263),
                            UpdatedBy = "System"
                        },
                        new
                        {
                            Id = 6,
                            AlbumId = 0,
                            ArtistId = 0,
                            CreatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9264),
                            CreatedBy = "System",
                            Duration = 0,
                            GenreId = 0,
                            Title = "7 rings",
                            UpdatedAt = new DateTime(2026, 1, 17, 16, 13, 3, 670, DateTimeKind.Local).AddTicks(9264),
                            UpdatedBy = "System"
                        });
                });

            modelBuilder.Entity("MeowsicLabzz.Components.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("MeowsicLabzz.Data.MeowsicLabzzUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FavoriteGenre")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43a2118e-d407-47a0-853b-ac3a9701e15e",
                            Email = "admin@localhost.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@LOCALHOST.COM",
                            NormalizedUserName = "ADMIN@LOCALHOST.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHajF87Bs4lVc2bzZm1oI0w5Ofexaz7snF2HJ9AUSIe106zw+PfeaoS885eEy5TZVQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "45b54756-9d46-4ff5-97b4-fcc61bc679b5",
                            TwoFactorEnabled = false,
                            UserName = "admin@localhost.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "ad2bcf0c-20db-474f-8407-5a6b159518ba",
                            Name = "Administrator",
                            NormalizedName = "ADMINISTRATOR"
                        },
                        new
                        {
                            Id = "bd2bcf0c-20db-474f-8407-5a6b159518bb",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "3781efa7-66dc-47f0-860f-e506d04102e4",
                            RoleId = "ad2bcf0c-20db-474f-8407-5a6b159518ba"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MeowsicLabzz.Data.MeowsicLabzzUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MeowsicLabzz.Data.MeowsicLabzzUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MeowsicLabzz.Data.MeowsicLabzzUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MeowsicLabzz.Data.MeowsicLabzzUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
